export const productReviews = [
  {
    id: 'r1',
    author: 'سارة م.',
    rating: 5,
    date: '١٢ أبريل ٢٠٢٥',
    title: 'أروع من المتوقع',
    content: 'الباقة فاقت كل التوقعات. طازجة، منسقة بإتقان، ووصلت في الموعد.',
    verified: true,
  },
  {
    id: 'r2',
    author: 'جمال ك.',
    rating: 5,
    date: '٢٨ مارس ٢٠٢٥',
    title: 'هدية ذكرى مثالية',
    content: 'زوجتي لم تتمالك من الفرحة. التغليف وحده يبعث الفخامة.',
    verified: true,
  },
  {
    id: 'r3',
    author: 'ليلى أ.',
    rating: 4,
    date: '١٥ مارس ٢٠٢٥',
    title: 'جميلة مع تأخير بسيط',
    content: 'الزهور بقيت أسبوعاً كاملاً. التوصيل تأخر ساعات لكن النتيجة تستحق.',
    verified: true,
  },
  {
    id: 'r4',
    author: 'إيمان ر.',
    rating: 5,
    date: '٢٠ فبراير ٢٠٢٥',
    title: 'تنسيق بمستوى المعارض',
    content: 'واضح أن كل ساق وُضعت بعناية فنان حقيقي.',
    verified: false,
  },
]
